.TH "ind" "1" "19th April, 2005" "ind" ""

.PP 
.SH "NAME"
ind \- Indent all output from subprocess
.PP 
.SH "SYNOPSIS"
\fBind\fP [ \-h ] [ \-p <fmt> ] [ \-a <fmt> ] [ \-P <fmt> ] [ \-A <fmt> ] <command> <args> \&.\&.\&.
.PP 
.SH "DESCRIPTION"
Indent all output from subprocess\&.
.PP 
.SH "OPTIONS"
.IP "\-a fmt"
Postfix stdout (default: \(dq\&\(dq\&)
.IP "\-A fmt"
Postfix stderr (default: \(dq\&\(dq\&)
.IP "\-\-copying"
Show the license (3\-clause BSD)
.IP "\-h, \-\-help"
Show help text
.IP "\-p fmt"
Prefix stdout (default: \(dq\&  \(dq\&)
.IP "\-P fmt"
Prefix stderr (default: \(dq\&>>\(dq\&)
.IP "\-v"
Increase verbosity (i\&.e\&. output more status/debug messages)
.IP "\-\-version"
Show version
.PP 
strftime() format, which is is normal text, except for \(cq\&%\(cq\&
which is the escape character\&.
.PP 
.IP "%%"
Insert % character\&.
.IP "%F"
Date\&. Example: 2011\-08\-01
.IP "%T"
Time\&. Example: 16:08:01
.IP "%Z"
Time Zone\&. Example: BST

.PP 
.SH "BUGS"
Does not emulate a terminal for programs that check that\&. This
means that the subprocess can\(cq\&t adjust the width of the output\&.
.PP 
Also, subprocesses that rewind the line (with \er) are not updated
in realtime\&.
.PP 
.SH "EXAMPLES"
Let\(cq\&s say you\(cq\&re running a script that has several stages, each producing
some status output\&. Now you can indent the output from the substages\&.
.PP 
<< snip >> 
.br 
echo \(dq\&Stage 1, reconfooberating the ablamatron\&.\&.\&.\(dq\& 
.br 
ind \-p \(dq\&\-\-> \(dq\& cat blah\&.txt 
.br 
.br 
echo \(dq\&Stage 2, burning image\&.\&.\&.\(dq\& 
.br 
ind \-p \(dq\&___ \(dq\& \-a \(dq\& ___\(dq\& growisofs \-Z /dev/hdc=randomcrap\&.img 
.br 
<< snip >> 
.br 

.PP 
This will produce the output: 
.br 
<< snip >> 
.br 
Stage 1, reconfooberating the ablamatron\&.\&.\&. 
.br 
\-\-> This is a text file 
.br 
\-\-> with only text in it\&. 
.br 
Stage 2, burning image\&.\&.\&. 
.br 
___ \&.\&.\&. ___ 
.br 
___ \&.\&.\&. ___ 
.br 
___ \&.\&.\&. ___ 
.br 
<< snip >> 
.br 

.PP 
.SH "SEE ALSO"
\fBsh(1)\fP, \fBctime(3)\fP
.PP 
.SH "COPYRIGHT"
Copyright (c) Thomas Habets 2005\&.
.PP 
.SH "AUTHOR"

	Ind was written by Thomas Habets <thomas@habets\&.se>\&. Send
        all bug reports his way\&.
